[phases.setup]
nixPkgs = ['python311', 'postgresql']
aptPkgs = ['python3-pip', 'python3-dev', 'build-essential']

[phases.install]
cmds = [
    '/usr/bin/python3 -m pip install --upgrade pip',
    'pip install Django>=5.0.6 djangorestframework django-cors-headers python-dotenv whitenoise psycopg2-binary dj-database-url gunicorn',
    'cd ideas_io && pip install -r requirements.txt'
]

[start]
cmd = 'cd ideas_io && PYTHONPATH=/app/ideas_io python manage.py migrate && PYTHONPATH=/app/ideas_io python manage.py collectstatic --noinput && PYTHONPATH=/app/ideas_io gunicorn ideas_io.wsgi:application --bind 0.0.0.0:$PORT'
