[phases.setup]
nixPkgs = ['python311', 'postgresql']
aptPkgs = ['python3-pip', 'python3-dev', 'build-essential']

[phases.install]
cmds = [
    'cd ideas_io',
    '/usr/bin/python3 -m pip install --upgrade pip',
    'pip install -r requirements.txt'
]

[start]
cmd = 'cd ideas_io && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn ideas_io.wsgi:application --bind 0.0.0.0:$PORT'
