[build]
builder = "nixpacks"
buildCommand = "pip install -r ./ideas_io/requirements.txt"

[deploy]
startCommand = "cd ideas_io && gunicorn --chdir ideas_io ideas_io.wsgi:application --log-file - --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
